defmodule ElixirEuler.Problem002 do
  @doc """
  Each new term in the Fibonacci sequence is generated by adding the previous
  two terms. By starting with 1 and 2, the first 10 terms will be:
  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  By considering the terms in the Fibonacci sequence whose values do not exceed
  four million, find the sum of the even-valued terms.
  """
  def solve(n) do
    Stream.iterate(0, fn(x) -> x + 1 end)
    |> Stream.map(fn(x) -> fib(x) end)
    |> Enum.take_while(fn(x) -> x < n end)
    |> Enum.filter(fn(x) -> rem(x, 2) == 0 end)
    |> Enum.reduce(0, fn(x, acc) -> x + acc end)
  end

  def fib(0), do: 0
  def fib(1), do: 1
  def fib(n), do: fib(n-1) + fib(n-2)
  def solve, do: IO.puts "002 -> #{inspect solve(4000000)}"
end
